spring:
  application:
    name: camel_integration_consumer
  main:
    lazy-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:camel_integration;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  hibernate:
    ddl-auto: create-drop
    dialect: org.hibernate.dialect.MySQL57Dialect
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

server:
  port: 9090

# Kafka Configuration
camel:
  component:
    kafka:
      brokers: ${BOOTSTRAP_SERVERS:http://192.168.1.20:9092}

# in class KafkaConfigurationProperties.java
# @ConfigurationProperties(prefix = "ru.perm.v.kafka")
# used as private String topicName;

ru.perm.v.camelkafka:
  topic-name: camel-integration

management:
  health:
    probes:
      enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 8781
